// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/orltom/questionnaire/backend/internal/identity (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -typed -package identity -destination mock_repositories_test.go gitlab.com/orltom/questionnaire/backend/internal/identity UserRepository
//

// Package identity is a generated GoMock package.
package identity

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *MockUserRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
	return &MockUserRepositoryCreateCall{Call: call}
}

// MockUserRepositoryCreateCall wrap *gomock.Call
type MockUserRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryCreateCall) Return(arg0 error) *MockUserRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryCreateCall) Do(f func(context.Context, User) error) *MockUserRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryCreateCall) DoAndReturn(f func(context.Context, User) error) *MockUserRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindBySubject mocks base method.
func (m *MockUserRepository) FindBySubject(ctx context.Context, issuer, subject string) (User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySubject", ctx, issuer, subject)
	ret0, _ := ret[0].(User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySubject indicates an expected call of FindBySubject.
func (mr *MockUserRepositoryMockRecorder) FindBySubject(ctx, issuer, subject any) *MockUserRepositoryFindBySubjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySubject", reflect.TypeOf((*MockUserRepository)(nil).FindBySubject), ctx, issuer, subject)
	return &MockUserRepositoryFindBySubjectCall{Call: call}
}

// MockUserRepositoryFindBySubjectCall wrap *gomock.Call
type MockUserRepositoryFindBySubjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryFindBySubjectCall) Return(arg0 User, arg1 error) *MockUserRepositoryFindBySubjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryFindBySubjectCall) Do(f func(context.Context, string, string) (User, error)) *MockUserRepositoryFindBySubjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryFindBySubjectCall) DoAndReturn(f func(context.Context, string, string) (User, error)) *MockUserRepositoryFindBySubjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
