//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"
	"uuid"

	"github.com/oapi-codegen/runtime"
)

// Defines values for Access.
const (
	AccessInvited Access = "invited"
	AccessPublic  Access = "public"
)

// Valid indicates whether the value is a known member of the Access enum.
func (e Access) Valid() bool {
	switch e {
	case AccessInvited:
		return true
	case AccessPublic:
		return true
	default:
		return false
	}
}

// Defines values for ChallengeState.
const (
	Finished  ChallengeState = "finished"
	Running   ChallengeState = "running"
	Scheduled ChallengeState = "scheduled"
)

// Valid indicates whether the value is a known member of the ChallengeState enum.
func (e ChallengeState) Valid() bool {
	switch e {
	case Finished:
		return true
	case Running:
		return true
	case Scheduled:
		return true
	default:
		return false
	}
}

// Defines values for Visibility.
const (
	VisibilityPrivate Visibility = "private"
	VisibilityPublic  Visibility = "public"
)

// Valid indicates whether the value is a known member of the Visibility enum.
func (e Visibility) Valid() bool {
	switch e {
	case VisibilityPrivate:
		return true
	case VisibilityPublic:
		return true
	default:
		return false
	}
}

// Access defines model for Access.
type Access string

// Answer defines model for Answer.
type Answer struct {
	Correct     bool   `json:"correct"`
	Description string `json:"description"`
	Position    int    `json:"position"`
}

// Challenge defines model for Challenge.
type Challenge struct {
	Access   Access         `json:"access"`
	ClosedAt *time.Time     `json:"closedAt,omitempty"`
	EndsAt   *time.Time     `json:"endsAt,omitempty"`
	Id       uuid.UUID      `json:"id"`
	Invitees []uuid.UUID    `json:"invitees"`
	Owner    uuid.UUID      `json:"owner"`
	Quiz     ChallengeQuiz  `json:"quiz"`
	StartsAt time.Time      `json:"startsAt"`
	State    ChallengeState `json:"state"`
}

// ChallengeAnswer defines model for ChallengeAnswer.
type ChallengeAnswer struct {
	Description string    `json:"description"`
	Id          uuid.UUID `json:"id"`
	Position    int       `json:"position"`
}

// ChallengeQuestion defines model for ChallengeQuestion.
type ChallengeQuestion struct {
	Answers     []ChallengeAnswer `json:"answers"`
	Description string            `json:"description"`
	Id          uuid.UUID         `json:"id"`
	Position    int               `json:"position"`
}

// ChallengeQuiz defines model for ChallengeQuiz.
type ChallengeQuiz struct {
	Questions []ChallengeQuestion `json:"questions"`
	QuizId    uuid.UUID           `json:"quizId"`
	Title     string              `json:"title"`
}

// ChallengeState defines model for ChallengeState.
type ChallengeState string

// CreateChallenge defines model for CreateChallenge.
type CreateChallenge struct {
	Access   Access       `json:"access"`
	EndsAt   *time.Time   `json:"endsAt,omitempty"`
	Invitees *[]uuid.UUID `json:"invitees,omitempty"`
	QuizId   uuid.UUID    `json:"quizId"`
	StartsAt time.Time    `json:"startsAt"`
}

// CreateQuestion defines model for CreateQuestion.
type CreateQuestion struct {
	Answers     []Answer   `json:"answers"`
	Description string     `json:"description"`
	Labels      *[]string  `json:"labels,omitempty"`
	Visibility  Visibility `json:"visibility"`
}

// CreateQuiz defines model for CreateQuiz.
type CreateQuiz struct {
	Description string          `json:"description"`
	Questions   *[]QuizQuestion `json:"questions,omitempty"`
	Title       string          `json:"title"`
	Visibility  Visibility      `json:"visibility"`
}

// Question defines model for Question.
type Question struct {
	Answers     []Answer   `json:"answers"`
	Description string     `json:"description"`
	Id          uuid.UUID  `json:"id"`
	Labels      []string   `json:"labels"`
	Owner       uuid.UUID  `json:"owner"`
	Visibility  Visibility `json:"visibility"`
}

// Quiz defines model for Quiz.
type Quiz struct {
	Description string         `json:"description"`
	Id          uuid.UUID      `json:"id"`
	Owner       uuid.UUID      `json:"owner"`
	Questions   []QuizQuestion `json:"questions"`
	Title       string         `json:"title"`
	Visibility  Visibility     `json:"visibility"`
}

// QuizQuestion defines model for QuizQuestion.
type QuizQuestion struct {
	Position   int       `json:"position"`
	QuestionId uuid.UUID `json:"questionId"`
}

// Result defines model for Result.
type Result struct {
	Points int       `json:"points"`
	UserId uuid.UUID `json:"userId"`
}

// SubmitAnswer defines model for SubmitAnswer.
type SubmitAnswer struct {
	AnswerId   uuid.UUID `json:"answerId"`
	QuestionId uuid.UUID `json:"questionId"`
}

// UpdateQuestion defines model for UpdateQuestion.
type UpdateQuestion struct {
	Answers     []Answer   `json:"answers"`
	Description string     `json:"description"`
	Labels      *[]string  `json:"labels,omitempty"`
	Visibility  Visibility `json:"visibility"`
}

// UpdateQuiz defines model for UpdateQuiz.
type UpdateQuiz struct {
	Description string         `json:"description"`
	Questions   []QuizQuestion `json:"questions"`
	Title       string         `json:"title"`
	Visibility  Visibility     `json:"visibility"`
}

// Visibility defines model for Visibility.
type Visibility string

// ChallengeId defines model for ChallengeId.
type ChallengeId = uuid.UUID

// QuestionId defines model for QuestionId.
type QuestionId = uuid.UUID

// QuizId defines model for QuizId.
type QuizId = uuid.UUID

// CreateChallengeJSONRequestBody defines body for CreateChallenge for application/json ContentType.
type CreateChallengeJSONRequestBody = CreateChallenge

// SubmitAnswerJSONRequestBody defines body for SubmitAnswer for application/json ContentType.
type SubmitAnswerJSONRequestBody = SubmitAnswer

// CreateQuestionJSONRequestBody defines body for CreateQuestion for application/json ContentType.
type CreateQuestionJSONRequestBody = CreateQuestion

// UpdateQuestionJSONRequestBody defines body for UpdateQuestion for application/json ContentType.
type UpdateQuestionJSONRequestBody = UpdateQuestion

// CreateQuizJSONRequestBody defines body for CreateQuiz for application/json ContentType.
type CreateQuizJSONRequestBody = CreateQuiz

// UpdateQuizJSONRequestBody defines body for UpdateQuiz for application/json ContentType.
type UpdateQuizJSONRequestBody = UpdateQuiz

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateChallenge Create challenge
	// (POST /challenges)
	CreateChallenge(w http.ResponseWriter, r *http.Request)
	// DeleteChallenge Delete challenge
	// (DELETE /challenges/{challengeId})
	DeleteChallenge(w http.ResponseWriter, r *http.Request, challengeId ChallengeId)
	// GetChallenge Get challenge
	// (GET /challenges/{challengeId})
	GetChallenge(w http.ResponseWriter, r *http.Request, challengeId ChallengeId)
	// SubmitAnswer Submit an answer
	// (POST /challenges/{challengeId}/answers)
	SubmitAnswer(w http.ResponseWriter, r *http.Request, challengeId ChallengeId)
	// CloseChallenge Close challenge
	// (POST /challenges/{challengeId}/close)
	CloseChallenge(w http.ResponseWriter, r *http.Request, challengeId ChallengeId)
	// GetChallengeResults Get challenge results
	// (GET /challenges/{challengeId}/results)
	GetChallengeResults(w http.ResponseWriter, r *http.Request, challengeId ChallengeId)
	// CreateQuestion Create question
	// (POST /questions)
	CreateQuestion(w http.ResponseWriter, r *http.Request)
	// DeleteQuestion Delete question
	// (DELETE /questions/{questionId})
	DeleteQuestion(w http.ResponseWriter, r *http.Request, questionId QuestionId)
	// GetQuestion Get question
	// (GET /questions/{questionId})
	GetQuestion(w http.ResponseWriter, r *http.Request, questionId QuestionId)
	// UpdateQuestion Update question
	// (PUT /questions/{questionId})
	UpdateQuestion(w http.ResponseWriter, r *http.Request, questionId QuestionId)
	// CreateQuiz Create quiz
	// (POST /quizzes)
	CreateQuiz(w http.ResponseWriter, r *http.Request)
	// DeleteQuiz Delete quiz
	// (DELETE /quizzes/{quizId})
	DeleteQuiz(w http.ResponseWriter, r *http.Request, quizId QuizId)
	// GetQuiz Get quiz
	// (GET /quizzes/{quizId})
	GetQuiz(w http.ResponseWriter, r *http.Request, quizId QuizId)
	// UpdateQuiz Update quiz
	// (PUT /quizzes/{quizId})
	UpdateQuiz(w http.ResponseWriter, r *http.Request, quizId QuizId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateChallenge operation middleware
func (siw *ServerInterfaceWrapper) CreateChallenge(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChallenge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChallenge operation middleware
func (siw *ServerInterfaceWrapper) DeleteChallenge(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "challengeId" -------------
	var challengeId ChallengeId

	err = runtime.BindStyledParameterWithOptions("simple", "challengeId", r.PathValue("challengeId"), &challengeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "challengeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChallenge(w, r, challengeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChallenge operation middleware
func (siw *ServerInterfaceWrapper) GetChallenge(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "challengeId" -------------
	var challengeId ChallengeId

	err = runtime.BindStyledParameterWithOptions("simple", "challengeId", r.PathValue("challengeId"), &challengeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "challengeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChallenge(w, r, challengeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitAnswer operation middleware
func (siw *ServerInterfaceWrapper) SubmitAnswer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "challengeId" -------------
	var challengeId ChallengeId

	err = runtime.BindStyledParameterWithOptions("simple", "challengeId", r.PathValue("challengeId"), &challengeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "challengeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitAnswer(w, r, challengeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CloseChallenge operation middleware
func (siw *ServerInterfaceWrapper) CloseChallenge(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "challengeId" -------------
	var challengeId ChallengeId

	err = runtime.BindStyledParameterWithOptions("simple", "challengeId", r.PathValue("challengeId"), &challengeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "challengeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CloseChallenge(w, r, challengeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChallengeResults operation middleware
func (siw *ServerInterfaceWrapper) GetChallengeResults(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "challengeId" -------------
	var challengeId ChallengeId

	err = runtime.BindStyledParameterWithOptions("simple", "challengeId", r.PathValue("challengeId"), &challengeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "challengeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChallengeResults(w, r, challengeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateQuestion operation middleware
func (siw *ServerInterfaceWrapper) CreateQuestion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateQuestion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteQuestion operation middleware
func (siw *ServerInterfaceWrapper) DeleteQuestion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "questionId" -------------
	var questionId QuestionId

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", r.PathValue("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteQuestion(w, r, questionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuestion operation middleware
func (siw *ServerInterfaceWrapper) GetQuestion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "questionId" -------------
	var questionId QuestionId

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", r.PathValue("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuestion(w, r, questionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateQuestion operation middleware
func (siw *ServerInterfaceWrapper) UpdateQuestion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "questionId" -------------
	var questionId QuestionId

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", r.PathValue("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateQuestion(w, r, questionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateQuiz operation middleware
func (siw *ServerInterfaceWrapper) CreateQuiz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateQuiz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteQuiz operation middleware
func (siw *ServerInterfaceWrapper) DeleteQuiz(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "quizId" -------------
	var quizId QuizId

	err = runtime.BindStyledParameterWithOptions("simple", "quizId", r.PathValue("quizId"), &quizId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quizId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteQuiz(w, r, quizId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuiz operation middleware
func (siw *ServerInterfaceWrapper) GetQuiz(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "quizId" -------------
	var quizId QuizId

	err = runtime.BindStyledParameterWithOptions("simple", "quizId", r.PathValue("quizId"), &quizId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quizId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuiz(w, r, quizId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateQuiz operation middleware
func (siw *ServerInterfaceWrapper) UpdateQuiz(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "quizId" -------------
	var quizId QuizId

	err = runtime.BindStyledParameterWithOptions("simple", "quizId", r.PathValue("quizId"), &quizId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quizId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateQuiz(w, r, quizId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/quizzes", wrapper.CreateQuiz)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/quizzes/{quizId}", wrapper.DeleteQuiz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quizzes/{quizId}", wrapper.GetQuiz)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/quizzes/{quizId}", wrapper.UpdateQuiz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/challenges", wrapper.CreateChallenge)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/challenges/{challengeId}", wrapper.DeleteChallenge)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/challenges/{challengeId}", wrapper.GetChallenge)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/challenges/{challengeId}/close", wrapper.CloseChallenge)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/challenges/{challengeId}/answers", wrapper.SubmitAnswer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/challenges/{challengeId}/results", wrapper.GetChallengeResults)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/questions", wrapper.CreateQuestion)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/questions/{questionId}", wrapper.DeleteQuestion)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/questions/{questionId}", wrapper.GetQuestion)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/questions/{questionId}", wrapper.UpdateQuestion)

	return m
}
