// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/orltom/questionnaire/backend/internal/quiz/application (interfaces: QuestionRepository,QuizRepository,QuestionLookupService,ChallengeRepository,ParticipationRepository,QuizFinder,QuestionFinder)
//
// Generated by this command:
//
//	mockgen -typed -package application -destination mock_repositories_test.go gitlab.com/orltom/questionnaire/backend/internal/quiz/application QuestionRepository,QuizRepository,QuestionLookupService,ChallengeRepository,ParticipationRepository,QuizFinder,QuestionFinder
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "gitlab.com/orltom/questionnaire/backend/internal/quiz/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockQuestionRepository is a mock of QuestionRepository interface.
type MockQuestionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionRepositoryMockRecorder
	isgomock struct{}
}

// MockQuestionRepositoryMockRecorder is the mock recorder for MockQuestionRepository.
type MockQuestionRepositoryMockRecorder struct {
	mock *MockQuestionRepository
}

// NewMockQuestionRepository creates a new mock instance.
func NewMockQuestionRepository(ctrl *gomock.Controller) *MockQuestionRepository {
	mock := &MockQuestionRepository{ctrl: ctrl}
	mock.recorder = &MockQuestionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionRepository) EXPECT() *MockQuestionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockQuestionRepository) Create(ctx context.Context, question domain.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, question)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockQuestionRepositoryMockRecorder) Create(ctx, question any) *MockQuestionRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuestionRepository)(nil).Create), ctx, question)
	return &MockQuestionRepositoryCreateCall{Call: call}
}

// MockQuestionRepositoryCreateCall wrap *gomock.Call
type MockQuestionRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryCreateCall) Return(arg0 error) *MockQuestionRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryCreateCall) Do(f func(context.Context, domain.Question) error) *MockQuestionRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryCreateCall) DoAndReturn(f func(context.Context, domain.Question) error) *MockQuestionRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockQuestionRepository) Delete(ctx context.Context, id domain.QuestionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQuestionRepositoryMockRecorder) Delete(ctx, id any) *MockQuestionRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQuestionRepository)(nil).Delete), ctx, id)
	return &MockQuestionRepositoryDeleteCall{Call: call}
}

// MockQuestionRepositoryDeleteCall wrap *gomock.Call
type MockQuestionRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryDeleteCall) Return(arg0 error) *MockQuestionRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryDeleteCall) Do(f func(context.Context, domain.QuestionID) error) *MockQuestionRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryDeleteCall) DoAndReturn(f func(context.Context, domain.QuestionID) error) *MockQuestionRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Find mocks base method.
func (m *MockQuestionRepository) Find(ctx context.Context, id domain.QuestionID) (domain.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockQuestionRepositoryMockRecorder) Find(ctx, id any) *MockQuestionRepositoryFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockQuestionRepository)(nil).Find), ctx, id)
	return &MockQuestionRepositoryFindCall{Call: call}
}

// MockQuestionRepositoryFindCall wrap *gomock.Call
type MockQuestionRepositoryFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryFindCall) Return(arg0 domain.Question, arg1 error) *MockQuestionRepositoryFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryFindCall) Do(f func(context.Context, domain.QuestionID) (domain.Question, error)) *MockQuestionRepositoryFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryFindCall) DoAndReturn(f func(context.Context, domain.QuestionID) (domain.Question, error)) *MockQuestionRepositoryFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockQuestionRepository) Update(ctx context.Context, question domain.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, question)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQuestionRepositoryMockRecorder) Update(ctx, question any) *MockQuestionRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQuestionRepository)(nil).Update), ctx, question)
	return &MockQuestionRepositoryUpdateCall{Call: call}
}

// MockQuestionRepositoryUpdateCall wrap *gomock.Call
type MockQuestionRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryUpdateCall) Return(arg0 error) *MockQuestionRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryUpdateCall) Do(f func(context.Context, domain.Question) error) *MockQuestionRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryUpdateCall) DoAndReturn(f func(context.Context, domain.Question) error) *MockQuestionRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockQuizRepository is a mock of QuizRepository interface.
type MockQuizRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuizRepositoryMockRecorder
	isgomock struct{}
}

// MockQuizRepositoryMockRecorder is the mock recorder for MockQuizRepository.
type MockQuizRepositoryMockRecorder struct {
	mock *MockQuizRepository
}

// NewMockQuizRepository creates a new mock instance.
func NewMockQuizRepository(ctrl *gomock.Controller) *MockQuizRepository {
	mock := &MockQuizRepository{ctrl: ctrl}
	mock.recorder = &MockQuizRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuizRepository) EXPECT() *MockQuizRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockQuizRepository) Create(ctx context.Context, quiz domain.Quiz) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, quiz)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockQuizRepositoryMockRecorder) Create(ctx, quiz any) *MockQuizRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuizRepository)(nil).Create), ctx, quiz)
	return &MockQuizRepositoryCreateCall{Call: call}
}

// MockQuizRepositoryCreateCall wrap *gomock.Call
type MockQuizRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuizRepositoryCreateCall) Return(arg0 error) *MockQuizRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuizRepositoryCreateCall) Do(f func(context.Context, domain.Quiz) error) *MockQuizRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuizRepositoryCreateCall) DoAndReturn(f func(context.Context, domain.Quiz) error) *MockQuizRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockQuizRepository) Delete(ctx context.Context, id domain.QuizID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQuizRepositoryMockRecorder) Delete(ctx, id any) *MockQuizRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQuizRepository)(nil).Delete), ctx, id)
	return &MockQuizRepositoryDeleteCall{Call: call}
}

// MockQuizRepositoryDeleteCall wrap *gomock.Call
type MockQuizRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuizRepositoryDeleteCall) Return(arg0 error) *MockQuizRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuizRepositoryDeleteCall) Do(f func(context.Context, domain.QuizID) error) *MockQuizRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuizRepositoryDeleteCall) DoAndReturn(f func(context.Context, domain.QuizID) error) *MockQuizRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Find mocks base method.
func (m *MockQuizRepository) Find(ctx context.Context, id domain.QuizID) (domain.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockQuizRepositoryMockRecorder) Find(ctx, id any) *MockQuizRepositoryFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockQuizRepository)(nil).Find), ctx, id)
	return &MockQuizRepositoryFindCall{Call: call}
}

// MockQuizRepositoryFindCall wrap *gomock.Call
type MockQuizRepositoryFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuizRepositoryFindCall) Return(arg0 domain.Quiz, arg1 error) *MockQuizRepositoryFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuizRepositoryFindCall) Do(f func(context.Context, domain.QuizID) (domain.Quiz, error)) *MockQuizRepositoryFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuizRepositoryFindCall) DoAndReturn(f func(context.Context, domain.QuizID) (domain.Quiz, error)) *MockQuizRepositoryFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockQuizRepository) Update(ctx context.Context, quiz domain.Quiz) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, quiz)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQuizRepositoryMockRecorder) Update(ctx, quiz any) *MockQuizRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQuizRepository)(nil).Update), ctx, quiz)
	return &MockQuizRepositoryUpdateCall{Call: call}
}

// MockQuizRepositoryUpdateCall wrap *gomock.Call
type MockQuizRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuizRepositoryUpdateCall) Return(arg0 error) *MockQuizRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuizRepositoryUpdateCall) Do(f func(context.Context, domain.Quiz) error) *MockQuizRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuizRepositoryUpdateCall) DoAndReturn(f func(context.Context, domain.Quiz) error) *MockQuizRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockQuestionLookupService is a mock of QuestionLookupService interface.
type MockQuestionLookupService struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionLookupServiceMockRecorder
	isgomock struct{}
}

// MockQuestionLookupServiceMockRecorder is the mock recorder for MockQuestionLookupService.
type MockQuestionLookupServiceMockRecorder struct {
	mock *MockQuestionLookupService
}

// NewMockQuestionLookupService creates a new mock instance.
func NewMockQuestionLookupService(ctrl *gomock.Controller) *MockQuestionLookupService {
	mock := &MockQuestionLookupService{ctrl: ctrl}
	mock.recorder = &MockQuestionLookupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionLookupService) EXPECT() *MockQuestionLookupServiceMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockQuestionLookupService) Exists(ctx context.Context, id domain.QuestionID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockQuestionLookupServiceMockRecorder) Exists(ctx, id any) *MockQuestionLookupServiceExistsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockQuestionLookupService)(nil).Exists), ctx, id)
	return &MockQuestionLookupServiceExistsCall{Call: call}
}

// MockQuestionLookupServiceExistsCall wrap *gomock.Call
type MockQuestionLookupServiceExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionLookupServiceExistsCall) Return(arg0 bool, arg1 error) *MockQuestionLookupServiceExistsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionLookupServiceExistsCall) Do(f func(context.Context, domain.QuestionID) (bool, error)) *MockQuestionLookupServiceExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionLookupServiceExistsCall) DoAndReturn(f func(context.Context, domain.QuestionID) (bool, error)) *MockQuestionLookupServiceExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockChallengeRepository is a mock of ChallengeRepository interface.
type MockChallengeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChallengeRepositoryMockRecorder
	isgomock struct{}
}

// MockChallengeRepositoryMockRecorder is the mock recorder for MockChallengeRepository.
type MockChallengeRepositoryMockRecorder struct {
	mock *MockChallengeRepository
}

// NewMockChallengeRepository creates a new mock instance.
func NewMockChallengeRepository(ctrl *gomock.Controller) *MockChallengeRepository {
	mock := &MockChallengeRepository{ctrl: ctrl}
	mock.recorder = &MockChallengeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallengeRepository) EXPECT() *MockChallengeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockChallengeRepository) Create(ctx context.Context, challenge domain.Challenge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, challenge)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockChallengeRepositoryMockRecorder) Create(ctx, challenge any) *MockChallengeRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChallengeRepository)(nil).Create), ctx, challenge)
	return &MockChallengeRepositoryCreateCall{Call: call}
}

// MockChallengeRepositoryCreateCall wrap *gomock.Call
type MockChallengeRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChallengeRepositoryCreateCall) Return(arg0 error) *MockChallengeRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChallengeRepositoryCreateCall) Do(f func(context.Context, domain.Challenge) error) *MockChallengeRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChallengeRepositoryCreateCall) DoAndReturn(f func(context.Context, domain.Challenge) error) *MockChallengeRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockChallengeRepository) Delete(ctx context.Context, id domain.ChallengeID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockChallengeRepositoryMockRecorder) Delete(ctx, id any) *MockChallengeRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockChallengeRepository)(nil).Delete), ctx, id)
	return &MockChallengeRepositoryDeleteCall{Call: call}
}

// MockChallengeRepositoryDeleteCall wrap *gomock.Call
type MockChallengeRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChallengeRepositoryDeleteCall) Return(arg0 error) *MockChallengeRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChallengeRepositoryDeleteCall) Do(f func(context.Context, domain.ChallengeID) error) *MockChallengeRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChallengeRepositoryDeleteCall) DoAndReturn(f func(context.Context, domain.ChallengeID) error) *MockChallengeRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Find mocks base method.
func (m *MockChallengeRepository) Find(ctx context.Context, id domain.ChallengeID) (domain.Challenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Challenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockChallengeRepositoryMockRecorder) Find(ctx, id any) *MockChallengeRepositoryFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockChallengeRepository)(nil).Find), ctx, id)
	return &MockChallengeRepositoryFindCall{Call: call}
}

// MockChallengeRepositoryFindCall wrap *gomock.Call
type MockChallengeRepositoryFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChallengeRepositoryFindCall) Return(arg0 domain.Challenge, arg1 error) *MockChallengeRepositoryFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChallengeRepositoryFindCall) Do(f func(context.Context, domain.ChallengeID) (domain.Challenge, error)) *MockChallengeRepositoryFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChallengeRepositoryFindCall) DoAndReturn(f func(context.Context, domain.ChallengeID) (domain.Challenge, error)) *MockChallengeRepositoryFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockChallengeRepository) Update(ctx context.Context, challenge domain.Challenge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, challenge)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockChallengeRepositoryMockRecorder) Update(ctx, challenge any) *MockChallengeRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockChallengeRepository)(nil).Update), ctx, challenge)
	return &MockChallengeRepositoryUpdateCall{Call: call}
}

// MockChallengeRepositoryUpdateCall wrap *gomock.Call
type MockChallengeRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChallengeRepositoryUpdateCall) Return(arg0 error) *MockChallengeRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChallengeRepositoryUpdateCall) Do(f func(context.Context, domain.Challenge) error) *MockChallengeRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChallengeRepositoryUpdateCall) DoAndReturn(f func(context.Context, domain.Challenge) error) *MockChallengeRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockParticipationRepository is a mock of ParticipationRepository interface.
type MockParticipationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockParticipationRepositoryMockRecorder
	isgomock struct{}
}

// MockParticipationRepositoryMockRecorder is the mock recorder for MockParticipationRepository.
type MockParticipationRepositoryMockRecorder struct {
	mock *MockParticipationRepository
}

// NewMockParticipationRepository creates a new mock instance.
func NewMockParticipationRepository(ctrl *gomock.Controller) *MockParticipationRepository {
	mock := &MockParticipationRepository{ctrl: ctrl}
	mock.recorder = &MockParticipationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipationRepository) EXPECT() *MockParticipationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockParticipationRepository) Create(ctx context.Context, participation domain.Participation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, participation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockParticipationRepositoryMockRecorder) Create(ctx, participation any) *MockParticipationRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParticipationRepository)(nil).Create), ctx, participation)
	return &MockParticipationRepositoryCreateCall{Call: call}
}

// MockParticipationRepositoryCreateCall wrap *gomock.Call
type MockParticipationRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParticipationRepositoryCreateCall) Return(arg0 error) *MockParticipationRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParticipationRepositoryCreateCall) Do(f func(context.Context, domain.Participation) error) *MockParticipationRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParticipationRepositoryCreateCall) DoAndReturn(f func(context.Context, domain.Participation) error) *MockParticipationRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByChallenge mocks base method.
func (m *MockParticipationRepository) FindByChallenge(ctx context.Context, id domain.ChallengeID) ([]domain.Participation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByChallenge", ctx, id)
	ret0, _ := ret[0].([]domain.Participation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByChallenge indicates an expected call of FindByChallenge.
func (mr *MockParticipationRepositoryMockRecorder) FindByChallenge(ctx, id any) *MockParticipationRepositoryFindByChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByChallenge", reflect.TypeOf((*MockParticipationRepository)(nil).FindByChallenge), ctx, id)
	return &MockParticipationRepositoryFindByChallengeCall{Call: call}
}

// MockParticipationRepositoryFindByChallengeCall wrap *gomock.Call
type MockParticipationRepositoryFindByChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParticipationRepositoryFindByChallengeCall) Return(arg0 []domain.Participation, arg1 error) *MockParticipationRepositoryFindByChallengeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParticipationRepositoryFindByChallengeCall) Do(f func(context.Context, domain.ChallengeID) ([]domain.Participation, error)) *MockParticipationRepositoryFindByChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParticipationRepositoryFindByChallengeCall) DoAndReturn(f func(context.Context, domain.ChallengeID) ([]domain.Participation, error)) *MockParticipationRepositoryFindByChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByUser mocks base method.
func (m *MockParticipationRepository) FindByUser(ctx context.Context, id domain.ChallengeID, user domain.UserID) (domain.Participation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUser", ctx, id, user)
	ret0, _ := ret[0].(domain.Participation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUser indicates an expected call of FindByUser.
func (mr *MockParticipationRepositoryMockRecorder) FindByUser(ctx, id, user any) *MockParticipationRepositoryFindByUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUser", reflect.TypeOf((*MockParticipationRepository)(nil).FindByUser), ctx, id, user)
	return &MockParticipationRepositoryFindByUserCall{Call: call}
}

// MockParticipationRepositoryFindByUserCall wrap *gomock.Call
type MockParticipationRepositoryFindByUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParticipationRepositoryFindByUserCall) Return(arg0 domain.Participation, arg1 error) *MockParticipationRepositoryFindByUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParticipationRepositoryFindByUserCall) Do(f func(context.Context, domain.ChallengeID, domain.UserID) (domain.Participation, error)) *MockParticipationRepositoryFindByUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParticipationRepositoryFindByUserCall) DoAndReturn(f func(context.Context, domain.ChallengeID, domain.UserID) (domain.Participation, error)) *MockParticipationRepositoryFindByUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockParticipationRepository) Update(ctx context.Context, participation domain.Participation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, participation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockParticipationRepositoryMockRecorder) Update(ctx, participation any) *MockParticipationRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockParticipationRepository)(nil).Update), ctx, participation)
	return &MockParticipationRepositoryUpdateCall{Call: call}
}

// MockParticipationRepositoryUpdateCall wrap *gomock.Call
type MockParticipationRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParticipationRepositoryUpdateCall) Return(arg0 error) *MockParticipationRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParticipationRepositoryUpdateCall) Do(f func(context.Context, domain.Participation) error) *MockParticipationRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParticipationRepositoryUpdateCall) DoAndReturn(f func(context.Context, domain.Participation) error) *MockParticipationRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockQuizFinder is a mock of QuizFinder interface.
type MockQuizFinder struct {
	ctrl     *gomock.Controller
	recorder *MockQuizFinderMockRecorder
	isgomock struct{}
}

// MockQuizFinderMockRecorder is the mock recorder for MockQuizFinder.
type MockQuizFinderMockRecorder struct {
	mock *MockQuizFinder
}

// NewMockQuizFinder creates a new mock instance.
func NewMockQuizFinder(ctrl *gomock.Controller) *MockQuizFinder {
	mock := &MockQuizFinder{ctrl: ctrl}
	mock.recorder = &MockQuizFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuizFinder) EXPECT() *MockQuizFinderMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockQuizFinder) Find(ctx context.Context, id domain.QuizID) (domain.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockQuizFinderMockRecorder) Find(ctx, id any) *MockQuizFinderFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockQuizFinder)(nil).Find), ctx, id)
	return &MockQuizFinderFindCall{Call: call}
}

// MockQuizFinderFindCall wrap *gomock.Call
type MockQuizFinderFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuizFinderFindCall) Return(arg0 domain.Quiz, arg1 error) *MockQuizFinderFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuizFinderFindCall) Do(f func(context.Context, domain.QuizID) (domain.Quiz, error)) *MockQuizFinderFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuizFinderFindCall) DoAndReturn(f func(context.Context, domain.QuizID) (domain.Quiz, error)) *MockQuizFinderFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockQuestionFinder is a mock of QuestionFinder interface.
type MockQuestionFinder struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionFinderMockRecorder
	isgomock struct{}
}

// MockQuestionFinderMockRecorder is the mock recorder for MockQuestionFinder.
type MockQuestionFinderMockRecorder struct {
	mock *MockQuestionFinder
}

// NewMockQuestionFinder creates a new mock instance.
func NewMockQuestionFinder(ctrl *gomock.Controller) *MockQuestionFinder {
	mock := &MockQuestionFinder{ctrl: ctrl}
	mock.recorder = &MockQuestionFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionFinder) EXPECT() *MockQuestionFinderMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockQuestionFinder) Find(ctx context.Context, id domain.QuestionID) (domain.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockQuestionFinderMockRecorder) Find(ctx, id any) *MockQuestionFinderFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockQuestionFinder)(nil).Find), ctx, id)
	return &MockQuestionFinderFindCall{Call: call}
}

// MockQuestionFinderFindCall wrap *gomock.Call
type MockQuestionFinderFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionFinderFindCall) Return(arg0 domain.Question, arg1 error) *MockQuestionFinderFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionFinderFindCall) Do(f func(context.Context, domain.QuestionID) (domain.Question, error)) *MockQuestionFinderFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionFinderFindCall) DoAndReturn(f func(context.Context, domain.QuestionID) (domain.Question, error)) *MockQuestionFinderFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
