// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/orltom/questionnaire/backend/internal/quiz/application (interfaces: QuestionRepository,QuizRepository,QuestionLookupService)
//
// Generated by this command:
//
//	mockgen -typed -package application -destination mock_repositories_test.go gitlab.com/orltom/questionnaire/backend/internal/quiz/application QuestionRepository,QuizRepository,QuestionLookupService
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "gitlab.com/orltom/questionnaire/backend/internal/quiz/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockQuestionRepository is a mock of QuestionRepository interface.
type MockQuestionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionRepositoryMockRecorder
	isgomock struct{}
}

// MockQuestionRepositoryMockRecorder is the mock recorder for MockQuestionRepository.
type MockQuestionRepositoryMockRecorder struct {
	mock *MockQuestionRepository
}

// NewMockQuestionRepository creates a new mock instance.
func NewMockQuestionRepository(ctrl *gomock.Controller) *MockQuestionRepository {
	mock := &MockQuestionRepository{ctrl: ctrl}
	mock.recorder = &MockQuestionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionRepository) EXPECT() *MockQuestionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockQuestionRepository) Create(ctx context.Context, question domain.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, question)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockQuestionRepositoryMockRecorder) Create(ctx, question any) *MockQuestionRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuestionRepository)(nil).Create), ctx, question)
	return &MockQuestionRepositoryCreateCall{Call: call}
}

// MockQuestionRepositoryCreateCall wrap *gomock.Call
type MockQuestionRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryCreateCall) Return(arg0 error) *MockQuestionRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryCreateCall) Do(f func(context.Context, domain.Question) error) *MockQuestionRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryCreateCall) DoAndReturn(f func(context.Context, domain.Question) error) *MockQuestionRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockQuestionRepository) Delete(ctx context.Context, id domain.QuestionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQuestionRepositoryMockRecorder) Delete(ctx, id any) *MockQuestionRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQuestionRepository)(nil).Delete), ctx, id)
	return &MockQuestionRepositoryDeleteCall{Call: call}
}

// MockQuestionRepositoryDeleteCall wrap *gomock.Call
type MockQuestionRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryDeleteCall) Return(arg0 error) *MockQuestionRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryDeleteCall) Do(f func(context.Context, domain.QuestionID) error) *MockQuestionRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryDeleteCall) DoAndReturn(f func(context.Context, domain.QuestionID) error) *MockQuestionRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Find mocks base method.
func (m *MockQuestionRepository) Find(ctx context.Context, id domain.QuestionID) (domain.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockQuestionRepositoryMockRecorder) Find(ctx, id any) *MockQuestionRepositoryFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockQuestionRepository)(nil).Find), ctx, id)
	return &MockQuestionRepositoryFindCall{Call: call}
}

// MockQuestionRepositoryFindCall wrap *gomock.Call
type MockQuestionRepositoryFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryFindCall) Return(arg0 domain.Question, arg1 error) *MockQuestionRepositoryFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryFindCall) Do(f func(context.Context, domain.QuestionID) (domain.Question, error)) *MockQuestionRepositoryFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryFindCall) DoAndReturn(f func(context.Context, domain.QuestionID) (domain.Question, error)) *MockQuestionRepositoryFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockQuestionRepository) Update(ctx context.Context, question domain.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, question)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQuestionRepositoryMockRecorder) Update(ctx, question any) *MockQuestionRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQuestionRepository)(nil).Update), ctx, question)
	return &MockQuestionRepositoryUpdateCall{Call: call}
}

// MockQuestionRepositoryUpdateCall wrap *gomock.Call
type MockQuestionRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryUpdateCall) Return(arg0 error) *MockQuestionRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryUpdateCall) Do(f func(context.Context, domain.Question) error) *MockQuestionRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryUpdateCall) DoAndReturn(f func(context.Context, domain.Question) error) *MockQuestionRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockQuizRepository is a mock of QuizRepository interface.
type MockQuizRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuizRepositoryMockRecorder
	isgomock struct{}
}

// MockQuizRepositoryMockRecorder is the mock recorder for MockQuizRepository.
type MockQuizRepositoryMockRecorder struct {
	mock *MockQuizRepository
}

// NewMockQuizRepository creates a new mock instance.
func NewMockQuizRepository(ctrl *gomock.Controller) *MockQuizRepository {
	mock := &MockQuizRepository{ctrl: ctrl}
	mock.recorder = &MockQuizRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuizRepository) EXPECT() *MockQuizRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockQuizRepository) Create(ctx context.Context, quiz domain.Quiz) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, quiz)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockQuizRepositoryMockRecorder) Create(ctx, quiz any) *MockQuizRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuizRepository)(nil).Create), ctx, quiz)
	return &MockQuizRepositoryCreateCall{Call: call}
}

// MockQuizRepositoryCreateCall wrap *gomock.Call
type MockQuizRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuizRepositoryCreateCall) Return(arg0 error) *MockQuizRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuizRepositoryCreateCall) Do(f func(context.Context, domain.Quiz) error) *MockQuizRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuizRepositoryCreateCall) DoAndReturn(f func(context.Context, domain.Quiz) error) *MockQuizRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockQuizRepository) Delete(ctx context.Context, id domain.QuizID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQuizRepositoryMockRecorder) Delete(ctx, id any) *MockQuizRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQuizRepository)(nil).Delete), ctx, id)
	return &MockQuizRepositoryDeleteCall{Call: call}
}

// MockQuizRepositoryDeleteCall wrap *gomock.Call
type MockQuizRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuizRepositoryDeleteCall) Return(arg0 error) *MockQuizRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuizRepositoryDeleteCall) Do(f func(context.Context, domain.QuizID) error) *MockQuizRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuizRepositoryDeleteCall) DoAndReturn(f func(context.Context, domain.QuizID) error) *MockQuizRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Find mocks base method.
func (m *MockQuizRepository) Find(ctx context.Context, id domain.QuizID) (domain.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockQuizRepositoryMockRecorder) Find(ctx, id any) *MockQuizRepositoryFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockQuizRepository)(nil).Find), ctx, id)
	return &MockQuizRepositoryFindCall{Call: call}
}

// MockQuizRepositoryFindCall wrap *gomock.Call
type MockQuizRepositoryFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuizRepositoryFindCall) Return(arg0 domain.Quiz, arg1 error) *MockQuizRepositoryFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuizRepositoryFindCall) Do(f func(context.Context, domain.QuizID) (domain.Quiz, error)) *MockQuizRepositoryFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuizRepositoryFindCall) DoAndReturn(f func(context.Context, domain.QuizID) (domain.Quiz, error)) *MockQuizRepositoryFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockQuizRepository) Update(ctx context.Context, quiz domain.Quiz) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, quiz)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQuizRepositoryMockRecorder) Update(ctx, quiz any) *MockQuizRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQuizRepository)(nil).Update), ctx, quiz)
	return &MockQuizRepositoryUpdateCall{Call: call}
}

// MockQuizRepositoryUpdateCall wrap *gomock.Call
type MockQuizRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuizRepositoryUpdateCall) Return(arg0 error) *MockQuizRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuizRepositoryUpdateCall) Do(f func(context.Context, domain.Quiz) error) *MockQuizRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuizRepositoryUpdateCall) DoAndReturn(f func(context.Context, domain.Quiz) error) *MockQuizRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockQuestionLookupService is a mock of QuestionLookupService interface.
type MockQuestionLookupService struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionLookupServiceMockRecorder
	isgomock struct{}
}

// MockQuestionLookupServiceMockRecorder is the mock recorder for MockQuestionLookupService.
type MockQuestionLookupServiceMockRecorder struct {
	mock *MockQuestionLookupService
}

// NewMockQuestionLookupService creates a new mock instance.
func NewMockQuestionLookupService(ctrl *gomock.Controller) *MockQuestionLookupService {
	mock := &MockQuestionLookupService{ctrl: ctrl}
	mock.recorder = &MockQuestionLookupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionLookupService) EXPECT() *MockQuestionLookupServiceMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockQuestionLookupService) Exists(ctx context.Context, id domain.QuestionID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockQuestionLookupServiceMockRecorder) Exists(ctx, id any) *MockQuestionLookupServiceExistsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockQuestionLookupService)(nil).Exists), ctx, id)
	return &MockQuestionLookupServiceExistsCall{Call: call}
}

// MockQuestionLookupServiceExistsCall wrap *gomock.Call
type MockQuestionLookupServiceExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionLookupServiceExistsCall) Return(arg0 bool, arg1 error) *MockQuestionLookupServiceExistsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionLookupServiceExistsCall) Do(f func(context.Context, domain.QuestionID) (bool, error)) *MockQuestionLookupServiceExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionLookupServiceExistsCall) DoAndReturn(f func(context.Context, domain.QuestionID) (bool, error)) *MockQuestionLookupServiceExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
