// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/orltom/questionnaire/backend/internal/quiz/infrastructure/rest (interfaces: quizService,questionService)
//
// Generated by this command:
//
//	mockgen -typed -package rest -destination mock_service_test.go gitlab.com/orltom/questionnaire/backend/internal/quiz/infrastructure/rest quizService,questionService
//

// Package rest is a generated GoMock package.
package rest

import (
	context "context"
	reflect "reflect"

	application "gitlab.com/orltom/questionnaire/backend/internal/quiz/application"
	domain "gitlab.com/orltom/questionnaire/backend/internal/quiz/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockquizService is a mock of quizService interface.
type MockquizService struct {
	ctrl     *gomock.Controller
	recorder *MockquizServiceMockRecorder
	isgomock struct{}
}

// MockquizServiceMockRecorder is the mock recorder for MockquizService.
type MockquizServiceMockRecorder struct {
	mock *MockquizService
}

// NewMockquizService creates a new mock instance.
func NewMockquizService(ctrl *gomock.Controller) *MockquizService {
	mock := &MockquizService{ctrl: ctrl}
	mock.recorder = &MockquizServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockquizService) EXPECT() *MockquizServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockquizService) Create(ctx context.Context, title, description string) (domain.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, title, description)
	ret0, _ := ret[0].(domain.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockquizServiceMockRecorder) Create(ctx, title, description any) *MockquizServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockquizService)(nil).Create), ctx, title, description)
	return &MockquizServiceCreateCall{Call: call}
}

// MockquizServiceCreateCall wrap *gomock.Call
type MockquizServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquizServiceCreateCall) Return(arg0 domain.Quiz, arg1 error) *MockquizServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquizServiceCreateCall) Do(f func(context.Context, string, string) (domain.Quiz, error)) *MockquizServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquizServiceCreateCall) DoAndReturn(f func(context.Context, string, string) (domain.Quiz, error)) *MockquizServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockquizService) Delete(ctx context.Context, id domain.QuizID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockquizServiceMockRecorder) Delete(ctx, id any) *MockquizServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockquizService)(nil).Delete), ctx, id)
	return &MockquizServiceDeleteCall{Call: call}
}

// MockquizServiceDeleteCall wrap *gomock.Call
type MockquizServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquizServiceDeleteCall) Return(arg0 error) *MockquizServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquizServiceDeleteCall) Do(f func(context.Context, domain.QuizID) error) *MockquizServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquizServiceDeleteCall) DoAndReturn(f func(context.Context, domain.QuizID) error) *MockquizServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockquizService) Get(ctx context.Context, id domain.QuizID) (domain.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockquizServiceMockRecorder) Get(ctx, id any) *MockquizServiceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockquizService)(nil).Get), ctx, id)
	return &MockquizServiceGetCall{Call: call}
}

// MockquizServiceGetCall wrap *gomock.Call
type MockquizServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquizServiceGetCall) Return(arg0 domain.Quiz, arg1 error) *MockquizServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquizServiceGetCall) Do(f func(context.Context, domain.QuizID) (domain.Quiz, error)) *MockquizServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquizServiceGetCall) DoAndReturn(f func(context.Context, domain.QuizID) (domain.Quiz, error)) *MockquizServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockquizService) Update(ctx context.Context, id domain.QuizID, title, description string, visibility domain.Visibility) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, title, description, visibility)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockquizServiceMockRecorder) Update(ctx, id, title, description, visibility any) *MockquizServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockquizService)(nil).Update), ctx, id, title, description, visibility)
	return &MockquizServiceUpdateCall{Call: call}
}

// MockquizServiceUpdateCall wrap *gomock.Call
type MockquizServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquizServiceUpdateCall) Return(arg0 error) *MockquizServiceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquizServiceUpdateCall) Do(f func(context.Context, domain.QuizID, string, string, domain.Visibility) error) *MockquizServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquizServiceUpdateCall) DoAndReturn(f func(context.Context, domain.QuizID, string, string, domain.Visibility) error) *MockquizServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockquestionService is a mock of questionService interface.
type MockquestionService struct {
	ctrl     *gomock.Controller
	recorder *MockquestionServiceMockRecorder
	isgomock struct{}
}

// MockquestionServiceMockRecorder is the mock recorder for MockquestionService.
type MockquestionServiceMockRecorder struct {
	mock *MockquestionService
}

// NewMockquestionService creates a new mock instance.
func NewMockquestionService(ctrl *gomock.Controller) *MockquestionService {
	mock := &MockquestionService{ctrl: ctrl}
	mock.recorder = &MockquestionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockquestionService) EXPECT() *MockquestionServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockquestionService) Create(ctx context.Context, req application.QuestionRequest) (domain.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(domain.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockquestionServiceMockRecorder) Create(ctx, req any) *MockquestionServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockquestionService)(nil).Create), ctx, req)
	return &MockquestionServiceCreateCall{Call: call}
}

// MockquestionServiceCreateCall wrap *gomock.Call
type MockquestionServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquestionServiceCreateCall) Return(arg0 domain.Question, arg1 error) *MockquestionServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquestionServiceCreateCall) Do(f func(context.Context, application.QuestionRequest) (domain.Question, error)) *MockquestionServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquestionServiceCreateCall) DoAndReturn(f func(context.Context, application.QuestionRequest) (domain.Question, error)) *MockquestionServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockquestionService) Delete(ctx context.Context, id domain.QuestionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockquestionServiceMockRecorder) Delete(ctx, id any) *MockquestionServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockquestionService)(nil).Delete), ctx, id)
	return &MockquestionServiceDeleteCall{Call: call}
}

// MockquestionServiceDeleteCall wrap *gomock.Call
type MockquestionServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquestionServiceDeleteCall) Return(arg0 error) *MockquestionServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquestionServiceDeleteCall) Do(f func(context.Context, domain.QuestionID) error) *MockquestionServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquestionServiceDeleteCall) DoAndReturn(f func(context.Context, domain.QuestionID) error) *MockquestionServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockquestionService) Get(ctx context.Context, id domain.QuestionID) (domain.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockquestionServiceMockRecorder) Get(ctx, id any) *MockquestionServiceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockquestionService)(nil).Get), ctx, id)
	return &MockquestionServiceGetCall{Call: call}
}

// MockquestionServiceGetCall wrap *gomock.Call
type MockquestionServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquestionServiceGetCall) Return(arg0 domain.Question, arg1 error) *MockquestionServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquestionServiceGetCall) Do(f func(context.Context, domain.QuestionID) (domain.Question, error)) *MockquestionServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquestionServiceGetCall) DoAndReturn(f func(context.Context, domain.QuestionID) (domain.Question, error)) *MockquestionServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockquestionService) Update(ctx context.Context, id domain.QuestionID, req application.QuestionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockquestionServiceMockRecorder) Update(ctx, id, req any) *MockquestionServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockquestionService)(nil).Update), ctx, id, req)
	return &MockquestionServiceUpdateCall{Call: call}
}

// MockquestionServiceUpdateCall wrap *gomock.Call
type MockquestionServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquestionServiceUpdateCall) Return(arg0 error) *MockquestionServiceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquestionServiceUpdateCall) Do(f func(context.Context, domain.QuestionID, application.QuestionRequest) error) *MockquestionServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquestionServiceUpdateCall) DoAndReturn(f func(context.Context, domain.QuestionID, application.QuestionRequest) error) *MockquestionServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
