// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/orltom/questionnaire/backend/internal/quiz/infrastructure/rest (interfaces: quizService,questionService,challengeService,participationService)
//
// Generated by this command:
//
//	mockgen -typed -package rest -destination mock_service_test.go gitlab.com/orltom/questionnaire/backend/internal/quiz/infrastructure/rest quizService,questionService,challengeService,participationService
//

// Package rest is a generated GoMock package.
package rest

import (
	context "context"
	reflect "reflect"
	time "time"

	application "gitlab.com/orltom/questionnaire/backend/internal/quiz/application"
	domain "gitlab.com/orltom/questionnaire/backend/internal/quiz/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockquizService is a mock of quizService interface.
type MockquizService struct {
	ctrl     *gomock.Controller
	recorder *MockquizServiceMockRecorder
	isgomock struct{}
}

// MockquizServiceMockRecorder is the mock recorder for MockquizService.
type MockquizServiceMockRecorder struct {
	mock *MockquizService
}

// NewMockquizService creates a new mock instance.
func NewMockquizService(ctrl *gomock.Controller) *MockquizService {
	mock := &MockquizService{ctrl: ctrl}
	mock.recorder = &MockquizServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockquizService) EXPECT() *MockquizServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockquizService) Create(ctx context.Context, actor domain.UserID, title, description string, visibility domain.Visibility) (domain.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, actor, title, description, visibility)
	ret0, _ := ret[0].(domain.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockquizServiceMockRecorder) Create(ctx, actor, title, description, visibility any) *MockquizServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockquizService)(nil).Create), ctx, actor, title, description, visibility)
	return &MockquizServiceCreateCall{Call: call}
}

// MockquizServiceCreateCall wrap *gomock.Call
type MockquizServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquizServiceCreateCall) Return(arg0 domain.Quiz, arg1 error) *MockquizServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquizServiceCreateCall) Do(f func(context.Context, domain.UserID, string, string, domain.Visibility) (domain.Quiz, error)) *MockquizServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquizServiceCreateCall) DoAndReturn(f func(context.Context, domain.UserID, string, string, domain.Visibility) (domain.Quiz, error)) *MockquizServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockquizService) Delete(ctx context.Context, actor domain.UserID, id domain.QuizID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, actor, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockquizServiceMockRecorder) Delete(ctx, actor, id any) *MockquizServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockquizService)(nil).Delete), ctx, actor, id)
	return &MockquizServiceDeleteCall{Call: call}
}

// MockquizServiceDeleteCall wrap *gomock.Call
type MockquizServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquizServiceDeleteCall) Return(arg0 error) *MockquizServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquizServiceDeleteCall) Do(f func(context.Context, domain.UserID, domain.QuizID) error) *MockquizServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquizServiceDeleteCall) DoAndReturn(f func(context.Context, domain.UserID, domain.QuizID) error) *MockquizServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockquizService) Get(ctx context.Context, actor domain.UserID, id domain.QuizID) (domain.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, actor, id)
	ret0, _ := ret[0].(domain.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockquizServiceMockRecorder) Get(ctx, actor, id any) *MockquizServiceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockquizService)(nil).Get), ctx, actor, id)
	return &MockquizServiceGetCall{Call: call}
}

// MockquizServiceGetCall wrap *gomock.Call
type MockquizServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquizServiceGetCall) Return(arg0 domain.Quiz, arg1 error) *MockquizServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquizServiceGetCall) Do(f func(context.Context, domain.UserID, domain.QuizID) (domain.Quiz, error)) *MockquizServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquizServiceGetCall) DoAndReturn(f func(context.Context, domain.UserID, domain.QuizID) (domain.Quiz, error)) *MockquizServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockquizService) Update(ctx context.Context, actor domain.UserID, id domain.QuizID, title, description string, visibility domain.Visibility) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, actor, id, title, description, visibility)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockquizServiceMockRecorder) Update(ctx, actor, id, title, description, visibility any) *MockquizServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockquizService)(nil).Update), ctx, actor, id, title, description, visibility)
	return &MockquizServiceUpdateCall{Call: call}
}

// MockquizServiceUpdateCall wrap *gomock.Call
type MockquizServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquizServiceUpdateCall) Return(arg0 error) *MockquizServiceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquizServiceUpdateCall) Do(f func(context.Context, domain.UserID, domain.QuizID, string, string, domain.Visibility) error) *MockquizServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquizServiceUpdateCall) DoAndReturn(f func(context.Context, domain.UserID, domain.QuizID, string, string, domain.Visibility) error) *MockquizServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockquestionService is a mock of questionService interface.
type MockquestionService struct {
	ctrl     *gomock.Controller
	recorder *MockquestionServiceMockRecorder
	isgomock struct{}
}

// MockquestionServiceMockRecorder is the mock recorder for MockquestionService.
type MockquestionServiceMockRecorder struct {
	mock *MockquestionService
}

// NewMockquestionService creates a new mock instance.
func NewMockquestionService(ctrl *gomock.Controller) *MockquestionService {
	mock := &MockquestionService{ctrl: ctrl}
	mock.recorder = &MockquestionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockquestionService) EXPECT() *MockquestionServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockquestionService) Create(ctx context.Context, actor domain.UserID, req application.QuestionRequest) (domain.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, actor, req)
	ret0, _ := ret[0].(domain.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockquestionServiceMockRecorder) Create(ctx, actor, req any) *MockquestionServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockquestionService)(nil).Create), ctx, actor, req)
	return &MockquestionServiceCreateCall{Call: call}
}

// MockquestionServiceCreateCall wrap *gomock.Call
type MockquestionServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquestionServiceCreateCall) Return(arg0 domain.Question, arg1 error) *MockquestionServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquestionServiceCreateCall) Do(f func(context.Context, domain.UserID, application.QuestionRequest) (domain.Question, error)) *MockquestionServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquestionServiceCreateCall) DoAndReturn(f func(context.Context, domain.UserID, application.QuestionRequest) (domain.Question, error)) *MockquestionServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockquestionService) Delete(ctx context.Context, actor domain.UserID, id domain.QuestionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, actor, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockquestionServiceMockRecorder) Delete(ctx, actor, id any) *MockquestionServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockquestionService)(nil).Delete), ctx, actor, id)
	return &MockquestionServiceDeleteCall{Call: call}
}

// MockquestionServiceDeleteCall wrap *gomock.Call
type MockquestionServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquestionServiceDeleteCall) Return(arg0 error) *MockquestionServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquestionServiceDeleteCall) Do(f func(context.Context, domain.UserID, domain.QuestionID) error) *MockquestionServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquestionServiceDeleteCall) DoAndReturn(f func(context.Context, domain.UserID, domain.QuestionID) error) *MockquestionServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockquestionService) Get(ctx context.Context, actor domain.UserID, id domain.QuestionID) (domain.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, actor, id)
	ret0, _ := ret[0].(domain.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockquestionServiceMockRecorder) Get(ctx, actor, id any) *MockquestionServiceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockquestionService)(nil).Get), ctx, actor, id)
	return &MockquestionServiceGetCall{Call: call}
}

// MockquestionServiceGetCall wrap *gomock.Call
type MockquestionServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquestionServiceGetCall) Return(arg0 domain.Question, arg1 error) *MockquestionServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquestionServiceGetCall) Do(f func(context.Context, domain.UserID, domain.QuestionID) (domain.Question, error)) *MockquestionServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquestionServiceGetCall) DoAndReturn(f func(context.Context, domain.UserID, domain.QuestionID) (domain.Question, error)) *MockquestionServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockquestionService) Update(ctx context.Context, actor domain.UserID, id domain.QuestionID, req application.QuestionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, actor, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockquestionServiceMockRecorder) Update(ctx, actor, id, req any) *MockquestionServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockquestionService)(nil).Update), ctx, actor, id, req)
	return &MockquestionServiceUpdateCall{Call: call}
}

// MockquestionServiceUpdateCall wrap *gomock.Call
type MockquestionServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockquestionServiceUpdateCall) Return(arg0 error) *MockquestionServiceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockquestionServiceUpdateCall) Do(f func(context.Context, domain.UserID, domain.QuestionID, application.QuestionRequest) error) *MockquestionServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockquestionServiceUpdateCall) DoAndReturn(f func(context.Context, domain.UserID, domain.QuestionID, application.QuestionRequest) error) *MockquestionServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockchallengeService is a mock of challengeService interface.
type MockchallengeService struct {
	ctrl     *gomock.Controller
	recorder *MockchallengeServiceMockRecorder
	isgomock struct{}
}

// MockchallengeServiceMockRecorder is the mock recorder for MockchallengeService.
type MockchallengeServiceMockRecorder struct {
	mock *MockchallengeService
}

// NewMockchallengeService creates a new mock instance.
func NewMockchallengeService(ctrl *gomock.Controller) *MockchallengeService {
	mock := &MockchallengeService{ctrl: ctrl}
	mock.recorder = &MockchallengeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchallengeService) EXPECT() *MockchallengeServiceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockchallengeService) Close(ctx context.Context, actor domain.UserID, id domain.ChallengeID, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, actor, id, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockchallengeServiceMockRecorder) Close(ctx, actor, id, now any) *MockchallengeServiceCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockchallengeService)(nil).Close), ctx, actor, id, now)
	return &MockchallengeServiceCloseCall{Call: call}
}

// MockchallengeServiceCloseCall wrap *gomock.Call
type MockchallengeServiceCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockchallengeServiceCloseCall) Return(arg0 error) *MockchallengeServiceCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockchallengeServiceCloseCall) Do(f func(context.Context, domain.UserID, domain.ChallengeID, time.Time) error) *MockchallengeServiceCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockchallengeServiceCloseCall) DoAndReturn(f func(context.Context, domain.UserID, domain.ChallengeID, time.Time) error) *MockchallengeServiceCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockchallengeService) Create(ctx context.Context, actor domain.UserID, req application.ChallengeRequest) (domain.Challenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, actor, req)
	ret0, _ := ret[0].(domain.Challenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockchallengeServiceMockRecorder) Create(ctx, actor, req any) *MockchallengeServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockchallengeService)(nil).Create), ctx, actor, req)
	return &MockchallengeServiceCreateCall{Call: call}
}

// MockchallengeServiceCreateCall wrap *gomock.Call
type MockchallengeServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockchallengeServiceCreateCall) Return(arg0 domain.Challenge, arg1 error) *MockchallengeServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockchallengeServiceCreateCall) Do(f func(context.Context, domain.UserID, application.ChallengeRequest) (domain.Challenge, error)) *MockchallengeServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockchallengeServiceCreateCall) DoAndReturn(f func(context.Context, domain.UserID, application.ChallengeRequest) (domain.Challenge, error)) *MockchallengeServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockchallengeService) Delete(ctx context.Context, actor domain.UserID, id domain.ChallengeID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, actor, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockchallengeServiceMockRecorder) Delete(ctx, actor, id any) *MockchallengeServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockchallengeService)(nil).Delete), ctx, actor, id)
	return &MockchallengeServiceDeleteCall{Call: call}
}

// MockchallengeServiceDeleteCall wrap *gomock.Call
type MockchallengeServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockchallengeServiceDeleteCall) Return(arg0 error) *MockchallengeServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockchallengeServiceDeleteCall) Do(f func(context.Context, domain.UserID, domain.ChallengeID) error) *MockchallengeServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockchallengeServiceDeleteCall) DoAndReturn(f func(context.Context, domain.UserID, domain.ChallengeID) error) *MockchallengeServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockchallengeService) Get(ctx context.Context, actor domain.UserID, id domain.ChallengeID) (domain.Challenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, actor, id)
	ret0, _ := ret[0].(domain.Challenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockchallengeServiceMockRecorder) Get(ctx, actor, id any) *MockchallengeServiceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockchallengeService)(nil).Get), ctx, actor, id)
	return &MockchallengeServiceGetCall{Call: call}
}

// MockchallengeServiceGetCall wrap *gomock.Call
type MockchallengeServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockchallengeServiceGetCall) Return(arg0 domain.Challenge, arg1 error) *MockchallengeServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockchallengeServiceGetCall) Do(f func(context.Context, domain.UserID, domain.ChallengeID) (domain.Challenge, error)) *MockchallengeServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockchallengeServiceGetCall) DoAndReturn(f func(context.Context, domain.UserID, domain.ChallengeID) (domain.Challenge, error)) *MockchallengeServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockparticipationService is a mock of participationService interface.
type MockparticipationService struct {
	ctrl     *gomock.Controller
	recorder *MockparticipationServiceMockRecorder
	isgomock struct{}
}

// MockparticipationServiceMockRecorder is the mock recorder for MockparticipationService.
type MockparticipationServiceMockRecorder struct {
	mock *MockparticipationService
}

// NewMockparticipationService creates a new mock instance.
func NewMockparticipationService(ctrl *gomock.Controller) *MockparticipationService {
	mock := &MockparticipationService{ctrl: ctrl}
	mock.recorder = &MockparticipationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockparticipationService) EXPECT() *MockparticipationServiceMockRecorder {
	return m.recorder
}

// Results mocks base method.
func (m *MockparticipationService) Results(ctx context.Context, actor domain.UserID, id domain.ChallengeID) ([]application.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Results", ctx, actor, id)
	ret0, _ := ret[0].([]application.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Results indicates an expected call of Results.
func (mr *MockparticipationServiceMockRecorder) Results(ctx, actor, id any) *MockparticipationServiceResultsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Results", reflect.TypeOf((*MockparticipationService)(nil).Results), ctx, actor, id)
	return &MockparticipationServiceResultsCall{Call: call}
}

// MockparticipationServiceResultsCall wrap *gomock.Call
type MockparticipationServiceResultsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockparticipationServiceResultsCall) Return(arg0 []application.Result, arg1 error) *MockparticipationServiceResultsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockparticipationServiceResultsCall) Do(f func(context.Context, domain.UserID, domain.ChallengeID) ([]application.Result, error)) *MockparticipationServiceResultsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockparticipationServiceResultsCall) DoAndReturn(f func(context.Context, domain.UserID, domain.ChallengeID) ([]application.Result, error)) *MockparticipationServiceResultsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Submit mocks base method.
func (m *MockparticipationService) Submit(ctx context.Context, actor domain.UserID, id domain.ChallengeID, questionID domain.QuestionID, answerID domain.AnswerID, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, actor, id, questionID, answerID, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// Submit indicates an expected call of Submit.
func (mr *MockparticipationServiceMockRecorder) Submit(ctx, actor, id, questionID, answerID, now any) *MockparticipationServiceSubmitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockparticipationService)(nil).Submit), ctx, actor, id, questionID, answerID, now)
	return &MockparticipationServiceSubmitCall{Call: call}
}

// MockparticipationServiceSubmitCall wrap *gomock.Call
type MockparticipationServiceSubmitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockparticipationServiceSubmitCall) Return(arg0 error) *MockparticipationServiceSubmitCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockparticipationServiceSubmitCall) Do(f func(context.Context, domain.UserID, domain.ChallengeID, domain.QuestionID, domain.AnswerID, time.Time) error) *MockparticipationServiceSubmitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockparticipationServiceSubmitCall) DoAndReturn(f func(context.Context, domain.UserID, domain.ChallengeID, domain.QuestionID, domain.AnswerID, time.Time) error) *MockparticipationServiceSubmitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
